import type { Category, CompleteProject, SiteSettings } from './supabase/types';

export const demoCategories: Category[] = [
  {
    id: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
    name_tr: 'Mimari & Gayrimenkul',
    name_en: 'Architecture & Real Estate',
    slug: 'architecture',
    sort_order: 0,
    created_at: '2026-08-26T13:44:47.440Z',
  },
  {
    id: 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e',
    name_tr: 'Otomotiv & Ticari',
    name_en: 'Automotive & Commercial',
    slug: 'automotive',
    sort_order: 1,
    created_at: '2026-08-26T13:44:47.440Z',
  },
  {
    id: 'c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f',
    name_tr: 'Sinematik & Havadan',
    name_en: 'Cinematic & Aerial',
    slug: 'cinematic',
    sort_order: 2,
    created_at: '2026-08-26T13:44:47.440Z',
  },
  {
    id: 'd4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a',
    name_tr: 'Etkinlik & Prodüksiyon',
    name_en: 'Events & Production',
    slug: 'events',
    sort_order: 3,
    created_at: '2026-08-26T13:44:47.440Z',
  },
];

export const demoProjects: CompleteProject[] = [
  {
    id: 'proj-1',
    title: 'Urban Residence',
    slug: 'urban-residence',
    description_tr: 'Metropolün kalbinde modern mimari keşif. Geometrik ışık oyunları, yapısal zarafet ve minimalist malzeme paleti.',
    description_en: 'A modern architectural exploration in the heart of the metropolis. Emphasizing geometric light play, structural elegance, and minimalist material palettes.',
    category_id: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
    client: 'Urban Living Group',
    location: 'Istanbul, Turkey',
    year: 2024,
    hero_aspect_ratio: '16:9',
    featured: true,
    published: true,
    sort_order: 1,
    created_at: '2026-08-26T12:00:00.000Z',
    updated_at: '2026-08-26T12:00:00.000Z',
    category: demoCategories[0],
    media: [
      {
        id: 'media-1',
        project_id: 'proj-1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1920&q=80',
        aspect_ratio: '16:9',
        width: 1920,
        height: 1080,
        is_hero: true,
        sort_order: 1,
        caption_tr: 'Urban Residence Dış Mimari',
        caption_en: 'Urban Residence Exterior Architecture',
        poster_url: null,
        created_at: '2026-08-26T12:00:00.000Z',
      },
      {
        id: 'media-2',
        project_id: 'proj-1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1080&q=80',
        aspect_ratio: '4:5',
        width: 1080,
        height: 1350,
        is_hero: false,
        sort_order: 2,
        caption_tr: 'Oturma Odası Doğal Işık ve Geometri',
        caption_en: 'Living Room Natural Light and Geometry',
        poster_url: null,
        created_at: '2026-08-26T12:00:00.000Z',
      },
      {
        id: 'media-3',
        project_id: 'proj-1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80',
        aspect_ratio: '16:9',
        width: 1920,
        height: 1080,
        is_hero: false,
        sort_order: 3,
        caption_tr: 'İç Avlu Yansıma Havuzu',
        caption_en: 'Courtyard Reflection Pool',
        poster_url: null,
        created_at: '2026-08-26T12:00:00.000Z',
      },
    ],
  },
  {
    id: 'proj-2',
    title: 'Coastal Villa',
    slug: 'coastal-villa',
    description_tr: 'Panoramik Ege manzaralı lüks sahil villası; dikey sinematik format ve editoryal kürasyon için tasarlandı.',
    description_en: 'Luxury seaside sanctuary with panoramic Aegean views, tailored for vertical cinematic format and editorial curation.',
    category_id: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
    client: 'Seaside Estates',
    location: 'Bodrum, Turkey',
    year: 2024,
    hero_aspect_ratio: '9:16',
    featured: true,
    published: true,
    sort_order: 2,
    created_at: '2026-08-26T12:00:00.000Z',
    updated_at: '2026-08-26T12:00:00.000Z',
    category: demoCategories[0],
    media: [
      {
        id: 'media-4',
        project_id: 'proj-2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1080&q=80',
        aspect_ratio: '9:16',
        width: 1080,
        height: 1920,
        is_hero: true,
        sort_order: 1,
        caption_tr: 'Sahil Villası Gün Batımı — 9:16 Portre',
        caption_en: 'Coastal Villa Sunset View - 9:16 Portrait',
        poster_url: null,
        created_at: '2026-08-26T12:00:00.000Z',
      },
      {
        id: 'media-5',
        project_id: 'proj-2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1613545325278-f24b0cae1224?w=1920&q=80',
        aspect_ratio: '16:9',
        width: 1920,
        height: 1080,
        is_hero: false,
        sort_order: 2,
        caption_tr: 'Sonsuzluk Havuzu Ufuk Çizgisi',
        caption_en: 'Infinity Pool Horizon',
        poster_url: null,
        created_at: '2026-08-26T12:00:00.000Z',
      },
    ],
  },
  {
    id: 'proj-3',
    title: 'BMW G20 Visual',
    slug: 'bmw-g20',
    description_tr: 'Yüksek hız hassasiyetini, mühendislik kıvrımlarını ve asfalt yansımalarını 21:9 sinematik geniş formatta yakalayan dinamik otomotiv sekansı.',
    description_en: 'Dynamic automotive sequence capturing high-speed precision, engineered curves, and tarmac reflections in expansive 21:9 ultrawide aspect ratio.',
    category_id: 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e',
    client: 'Auto Showroom',
    location: 'Izmir, Turkey',
    year: 2024,
    hero_aspect_ratio: '21:9',
    featured: true,
    published: true,
    sort_order: 3,
    created_at: '2026-08-26T12:00:00.000Z',
    updated_at: '2026-08-26T12:00:00.000Z',
    category: demoCategories[1],
    media: [
      {
        id: 'media-6',
        project_id: 'proj-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=2560&q=80',
        aspect_ratio: '21:9',
        width: 2560,
        height: 1080,
        is_hero: true,
        sort_order: 1,
        caption_tr: 'BMW G20 Sinematik Pist Hareketi',
        caption_en: 'BMW G20 Ultrawide Cinematic Track Motion',
        poster_url: null,
        created_at: '2026-08-26T12:00:00.000Z',
      },
    ],
  },
  {
    id: 'proj-4',
    title: 'Minimal Café',
    slug: 'minimal-cafe',
    description_tr: 'Modern bir kafe iç mekanının ve nitelikli kahve ritüellerinin dengeli 1:1 ve 3:4 editoryal kompozisyonla estetik sunumu.',
    description_en: 'Clean aesthetic representation of a modern café interior and artisan coffee rituals in a balanced 1:1 and 3:4 editorial composition.',
    category_id: 'c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f',
    client: 'Brew Co.',
    location: 'Istanbul, Turkey',
    year: 2023,
    hero_aspect_ratio: '1:1',
    featured: false,
    published: true,
    sort_order: 4,
    created_at: '2026-08-26T12:00:00.000Z',
    updated_at: '2026-08-26T12:00:00.000Z',
    category: demoCategories[2],
    media: [
      {
        id: 'media-7',
        project_id: 'proj-4',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1080&q=80',
        aspect_ratio: '1:1',
        width: 1080,
        height: 1080,
        is_hero: true,
        sort_order: 1,
        caption_tr: 'Minimalist Kahve Barı Mimarisi',
        caption_en: 'Minimalist Coffee Bar Architecture',
        poster_url: null,
        created_at: '2026-08-26T12:00:00.000Z',
      },
    ],
  },
];

export const demoSiteSettings: SiteSettings = {
  id: 'settings-1',
  site_title: {
    tr: 'BAYRAKTAR CREATIVE — Premium Görsel Prodüksiyon',
    en: 'BAYRAKTAR CREATIVE — Premium Visual Production',
  },
  tagline: 'Visual Stories for Brands, Spaces and People',
  phone: '+90 5XX XXX XX XX',
  email: 'hello@bayraktarcreative.com',
  instagram: 'https://instagram.com/bayraktarcreative',
  whatsapp: '+905551234567',
  about_text: 'A creative production studio built around visual storytelling. We turn spaces, people, and moments into cinematic visual experiences across real estate, automotive, commercial films, and digital platforms.',
  contact_text: 'Available for commissions and projects worldwide. Let us know what you want to bring to life.',
  footer_text: '© 2026 BAYRAKTAR CREATIVE. ALL RIGHTS RESERVED.',
  seo_title: 'BAYRAKTAR CREATIVE | Visual Production Studio',
  seo_description: 'Premium visual production studio specializing in real estate, commercial, automotive, and portrait cinematography and photography.',
  og_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
  social_links: {
    instagram: 'https://instagram.com/bayraktarcreative',
    vimeo: 'https://vimeo.com',
    youtube: 'https://youtube.com',
  },
  updated_at: '2026-08-26T12:00:00.000Z',
};
