import type { Category, CompleteProject, SiteSettings } from './supabase/queries';

export const demoCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Real Estate',
    slug: 'real-estate',
    description: 'Cinematic architectural and luxury estate films and photography.',
    sort_order: 1,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    name: 'Automotive',
    slug: 'automotive',
    description: 'High-speed motion visuals and commercial automotive cinematography.',
    sort_order: 2,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    name: 'Commercial & Brand',
    slug: 'commercial',
    description: 'Narrative brand campaigns and product showcases.',
    sort_order: 3,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    name: 'Drone & Aerial',
    slug: 'drone',
    description: 'High-altitude perspectives, FPV sequences, and landscape geometry.',
    sort_order: 4,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoProjects: CompleteProject[] = [
  {
    id: 'proj-1',
    title: 'Urban Residence',
    slug: 'urban-residence',
    description: 'A modern architectural exploration in the heart of the metropolis. Emphasizing geometric light play, structural elegance, and minimalist material palettes.',
    category_id: 'cat-1',
    client: 'Urban Living Group',
    location: 'Istanbul, Turkey',
    project_date: '2024-03-15',
    is_published: true,
    is_featured: true,
    featured_order: 1,
    presentation_style: 'landscape',
    sort_order: 1,
    external_url: null,
    tags: ['Architecture', 'Real Estate', 'Cinematography', 'Interior'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[0],
    media: [
      {
        id: 'media-1',
        project_id: 'proj-1',
        media_type: 'image',
        storage_key: 'demo/urban-1.jpg',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1920&q=80',
        thumbnail_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=70',
        poster_url: null,
        mime_type: 'image/jpeg',
        file_size: 2450000,
        width: 1920,
        height: 1080,
        duration: null,
        sort_order: 1,
        is_cover: true,
        presentation_override: 'landscape',
        alt_text: 'Urban Residence Exterior Architecture',
        created_at: new Date().toISOString(),
      },
      {
        id: 'media-2',
        project_id: 'proj-1',
        media_type: 'image',
        storage_key: 'demo/urban-2.jpg',
        url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1080&q=80',
        thumbnail_url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&q=70',
        poster_url: null,
        mime_type: 'image/jpeg',
        file_size: 1890000,
        width: 1080,
        height: 1350,
        duration: null,
        sort_order: 2,
        is_cover: false,
        presentation_override: 'portrait',
        alt_text: 'Living Room Natural Light and Geometry',
        created_at: new Date().toISOString(),
      },
      {
        id: 'media-3',
        project_id: 'proj-1',
        media_type: 'image',
        storage_key: 'demo/urban-3.jpg',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80',
        thumbnail_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=70',
        poster_url: null,
        mime_type: 'image/jpeg',
        file_size: 2100000,
        width: 1920,
        height: 1080,
        duration: null,
        sort_order: 3,
        is_cover: false,
        presentation_override: 'landscape',
        alt_text: 'Courtyard Reflection Pool',
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'proj-2',
    title: 'Coastal Villa',
    slug: 'coastal-villa',
    description: 'Luxury seaside sanctuary with panoramic Aegean views, tailored for vertical cinematic format and editorial curation.',
    category_id: 'cat-1',
    client: 'Seaside Estates',
    location: 'Bodrum, Turkey',
    project_date: '2024-02-10',
    is_published: true,
    is_featured: true,
    featured_order: 2,
    presentation_style: 'portrait',
    sort_order: 2,
    external_url: null,
    tags: ['Luxury', 'Villa', 'Aegean', '9:16', 'Reels'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[0],
    media: [
      {
        id: 'media-4',
        project_id: 'proj-2',
        media_type: 'image',
        storage_key: 'demo/coastal-1.jpg',
        url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1080&q=80',
        thumbnail_url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=600&q=70',
        poster_url: null,
        mime_type: 'image/jpeg',
        file_size: 2200000,
        width: 1080,
        height: 1920,
        duration: null,
        sort_order: 1,
        is_cover: true,
        presentation_override: 'portrait',
        alt_text: 'Coastal Villa Sunset View - 9:16 Portrait',
        created_at: new Date().toISOString(),
      },
      {
        id: 'media-5',
        project_id: 'proj-2',
        media_type: 'image',
        storage_key: 'demo/coastal-2.jpg',
        url: 'https://images.unsplash.com/photo-1613545325278-f24b0cae1224?w=1920&q=80',
        thumbnail_url: 'https://images.unsplash.com/photo-1613545325278-f24b0cae1224?w=600&q=70',
        poster_url: null,
        mime_type: 'image/jpeg',
        file_size: 2400000,
        width: 1920,
        height: 1080,
        duration: null,
        sort_order: 2,
        is_cover: false,
        presentation_override: 'landscape',
        alt_text: 'Infinity Pool Horizon',
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'proj-3',
    title: 'BMW G20 Visual',
    slug: 'bmw-g20',
    description: 'Dynamic automotive sequence capturing high-speed precision, engineered curves, and tarmac reflections in expansive 21:9 ultrawide aspect ratio.',
    category_id: 'cat-2',
    client: 'Auto Showroom',
    location: 'Izmir, Turkey',
    project_date: '2024-01-20',
    is_published: true,
    is_featured: true,
    featured_order: 3,
    presentation_style: 'wide',
    sort_order: 3,
    external_url: null,
    tags: ['Automotive', 'Cinema', '21:9', 'Speed', 'Editorial'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[1],
    media: [
      {
        id: 'media-6',
        project_id: 'proj-3',
        media_type: 'image',
        storage_key: 'demo/bmw-1.jpg',
        url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=2560&q=80',
        thumbnail_url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&q=70',
        poster_url: null,
        mime_type: 'image/jpeg',
        file_size: 3100000,
        width: 2560,
        height: 1080,
        duration: null,
        sort_order: 1,
        is_cover: true,
        presentation_override: 'ultrawide',
        alt_text: 'BMW G20 Ultrawide Cinematic Track Motion',
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'proj-4',
    title: 'Minimal Café',
    slug: 'minimal-cafe',
    description: 'Clean aesthetic representation of a modern café interior and artisan coffee rituals in a balanced 1:1 and 3:4 editorial composition.',
    category_id: 'cat-3',
    client: 'Brew Co.',
    location: 'Istanbul, Turkey',
    project_date: '2023-11-28',
    is_published: true,
    is_featured: false,
    featured_order: 4,
    presentation_style: 'square',
    sort_order: 4,
    external_url: null,
    tags: ['Interior', 'Commercial', 'Food & Beverage', 'Lifestyle'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[2],
    media: [
      {
        id: 'media-7',
        project_id: 'proj-4',
        media_type: 'image',
        storage_key: 'demo/cafe-1.jpg',
        url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1080&q=80',
        thumbnail_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&q=70',
        poster_url: null,
        mime_type: 'image/jpeg',
        file_size: 1750000,
        width: 1080,
        height: 1080,
        duration: null,
        sort_order: 1,
        is_cover: true,
        presentation_override: 'square',
        alt_text: 'Minimalist Coffee Bar Architecture',
        created_at: new Date().toISOString(),
      },
    ],
  },
];

export const demoSiteSettings: SiteSettings = {
  id: 'settings-1',
  site_title: 'BAYRAKTAR CREATIVE',
  tagline: 'Visual Stories for Brands, Spaces and People',
  phone: '+90 (555) 123 45 67',
  email: 'hello@bayraktarcreative.com',
  instagram: 'https://instagram.com/bayraktarcreative',
  whatsapp: '+905551234567',
  about_text: 'A creative production studio built around visual storytelling. We turn spaces, people, and moments into cinematic visual experiences across real estate, automotive, commercial films, and digital platforms.',
  contact_text: 'Available for commissions and projects worldwide. Let us know what you want to bring to life.',
  footer_text: '© 2026 BAYRAKTAR CREATIVE. ALL RIGHTS RESERVED.',
  seo_title: 'BAYRAKTAR CREATIVE | Visual Production Studio',
  seo_description: 'Premium visual production studio specializing in real estate, commercial, automotive, and portrait cinematography and photography.',
  og_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
  updated_at: new Date().toISOString(),
};
